#!/bin/bash

for file_path in "$@"
do
	[[ ${file_path} == /* ]] && abs_path="$(dirname ${file_path})" || abs_path="$(pwd $(dirname ${file_path}))/$(dirname ${file_path})"
	abs_path="${abs_path}/$(basename ${file_path})"
	echo "${abs_path}" >> "${USER_STRUCT_PERS_FILES_LIST}"
done
